[package]
name = "flappy_dragon"
version = "0.1.0"
edition = "2021"
authors = ["Tonoy Akanda <tonoy.sust@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.7"
